export interface Plant {
  id: string;
  name: string;
  scientificName: string;
  benefits: string[];
  usage: string;
  activePrinciples: string;
  care: string;
  image: string;
  category: string;
  codigo: string;
  estado: string;
  cantidad: number;
}

export const plantsData: Plant[] = [
  {
    "id": "cebolla",
    "name": "Cebolla",
    "scientificName": "Allium cepa",
    "benefits": ["Expectorante", "Antiséptico", "Hipocolesterolemiante", "Anticoagulante", "Hipotensor"],
    "usage": "100g diario de bulbos frescos durante las comidas.",
    "activePrinciples": "Compuestos organoazufrados (alicina), flavonoides (quercetina), fructosanos.",
    "care": "Pleno sol, riego moderado. Suelo bien drenado.",
    "image": "https://images.unsplash.com/photo-1508747703725-719777637510?w=800&q=80&auto=format&fit=crop",
    "category": "Expectorante",
    "codigo": "PL-001",
    "estado": "Bueno",
    "cantidad": 15
  },
  {
    "id": "ajo",
    "name": "Ajo",
    "scientificName": "Allium sativum",
    "benefits": ["Antihipertensivo", "Hipolipemiante", "Diurético", "Bactericida", "Antiviral", "Anticoagulante"],
    "usage": "Dosis de 2-3 dientes diarios.",
    "activePrinciples": "Alicina, aliarina, vitaminas A, B y C, minerales (selenio).",
    "care": "Requiere sol directo, riego escaso y suelo con buen drenaje.",
    "image": "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=800&q=80&auto=format&fit=crop",
    "category": "Antiséptica",
    "codigo": "PL-002",
    "estado": "Bueno",
    "cantidad": 20
  },
  {
    "id": "aloe-vera",
    "name": "Aloe Vera",
    "scientificName": "Aloe barbadensis M.",
    "benefits": ["Cicatrizante", "Laxante", "Hidratante", "Antiinflamatorio"],
    "usage": "Uso interno (10-30 mg derivados hidroxiantracénicos para estreñimiento). Uso externo (gel directo sobre lesión).",
    "activePrinciples": "Aloína, derivados hidroxiantracénicos, mucílagos, barbaloína.",
    "care": "Luz solar indirecta, riego muy escaso (cada 2-3 semanas) y evitar heladas.",
    "image": "https://images.unsplash.com/photo-1684913127590-54e08d09a34b?w=800&q=80&auto=format&fit=crop",
    "category": "Cicatrizante",
    "codigo": "PL-003",
    "estado": "Bueno",
    "cantidad": 25
  },
  {
    "id": "cedron",
    "name": "Cedrón",
    "scientificName": "Aloysia triphylla (L'Herit.) Britt.",
    "benefits": ["Reconfortante", "Digestivo", "Calmante", "Antiespasmódico"],
    "usage": "Infusión de hojas. 45 mL de decocto al día.",
    "activePrinciples": "Aceite esencial rico en citral, limoneno, geraniol y verbenona.",
    "care": "Pleno sol, suelo fértil y riego moderado. Proteger del viento frío.",
    "image": "https://media.admagazine.com/photos/68c4e3ffd658915ffc714b18/1:1/w_2008,h_2008,c_limit/cedr%C3%B3n-significado.jpg",
    "category": "Calmante",
    "codigo": "PL-004",
    "estado": "Bueno",
    "cantidad": 18
  },
  {
    "id": "borraja",
    "name": "Borraja",
    "scientificName": "Borago officinalis L.",
    "benefits": ["Sudorífico", "Emoliente", "Diurético", "Expectorante"],
    "usage": "Infusión (10 g/L). 1 a 2 cucharaditas de té de flores para una taza de agua recién hervida.",
    "activePrinciples": "Mucílagos, taninos, flavonoides, sales de potasio, alcaloides pirrolizidínicos.",
    "care": "Sol directo, riego regular. Crece fácilmente de semilla en suelos húmedos.",
    "image": "https://www.ballchile.cl/wp-content/uploads/2023/03/borraja.jpg",
    "category": "Expectorante",
    "codigo": "PL-005",
    "estado": "Estable",
    "cantidad": 10
  },
  {
    "id": "matico",
    "name": "Matico",
    "scientificName": "Buddleja globosa Hope",
    "benefits": ["Diurético", "Antiinflamatorio", "Antiséptico local", "Cicatrizante"],
    "usage": "Infusión de uso interno y externo: 1 a 2 hojas medianas por taza de agua recién hervida.",
    "activePrinciples": "Flavonoides, taninos, compuestos terpénicos, aceites esenciales.",
    "care": "Pleno sol o semisombra, riego regular and poda después de florecer.",
    "image": "https://www.radioimagina.cl/wp-content/uploads/2021/08/Matico.png",
    "category": "Cicatrizante",
    "codigo": "PL-006",
    "estado": "Bueno",
    "cantidad": 32
  },
  {
    "id": "calendula",
    "name": "Caléndula",
    "scientificName": "Calendula officinalis L.",
    "benefits": ["Cicatrizante", "Antiséptica", "Antiinflamatoria"],
    "usage": "Infusión de 2g de droga en 150-200 mL de agua (compresas), tintura o pomada externa.",
    "activePrinciples": "Flavonoides, triterpenos, saponinas, carotenos, aceites esenciales.",
    "care": "Pleno sol o semisombra, riego regular, suelo con buen drenaje.",
    "image": "https://images.unsplash.com/photo-1632602304887-8439a8a14f37?w=800&q=80&auto=format&fit=crop",
    "category": "Cicatrizante",
    "codigo": "PL-007",
    "estado": "Bueno",
    "cantidad": 15
  },
  {
    "id": "manzanilla",
    "name": "Manzanilla",
    "scientificName": "Chamomilla recutita",
    "benefits": ["Tónico estomacal", "Antiséptico", "Antiespasmódico", "Antiinflamatorio", "Calmante"],
    "usage": "Infusión se prepara con 1 cucharadita de té del vegetal para una taza de agua hervida.",
    "activePrinciples": "Aceite esencial (chamazuleno), flavonoides (apigenina), bisabolol.",
    "care": "Pleno sol, riego moderado y suelo suelto.",
    "image": "https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=800&q=80&auto=format&fit=crop",
    "category": "Calmante",
    "codigo": "PL-008",
    "estado": "Crítico",
    "cantidad": 6
  },
  {
    "id": "limpia-plata",
    "name": "Limpia Plata",
    "scientificName": "Equisetum sp.",
    "benefits": ["Diurético", "Hemostático", "Cicatrizante", "Suplemento mineral"],
    "usage": "Beber 1 taza de infusión 3 veces al día. Decocto para uso externo.",
    "activePrinciples": "Sílice (silicio), sales de potasio, flavonoides, saponinas.",
    "care": "Mucha humedad, suelo arcilloso o áreas pantanosas con sombra parcial.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrjed3Ogs8j_cgbCffXyGAA5Eiwo90NDiUtw&s",
    "category": "Diurética",
    "codigo": "PL-009",
    "estado": "Bueno",
    "cantidad": 14
  },
  {
    "id": "hinojo",
    "name": "Hinojo",
    "scientificName": "Foeniculum sp.pl.",
    "benefits": ["Digestivo", "Expectorante", "Antitusivo", "Carminativo"],
    "usage": "Infusión de frutos. Adultos: 5-7g de frutos al día. Niños: dosis reducida según edad.",
    "activePrinciples": "Aceite esencial rico en anetol y fenchona, flavonoides.",
    "care": "Pleno sol, suelo suelto y fértil. Tolera sequías una vez establecido.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Fennel_flower_heads.jpg/250px-Fennel_flower_heads.jpg?utm_source=species.wikimedia.org&utm_campaign=parser&utm_content=thumbnail",
    "category": "Digestiva",
    "codigo": "PL-010",
    "estado": "Bueno",
    "cantidad": 11
  },
  {
    "id": "hierba-de-san-juan",
    "name": "Hierba de San Juan",
    "scientificName": "Hypericum perforatum L.",
    "benefits": ["Diurético", "Antidepresivo", "Calmante", "Cicatrizante"],
    "usage": "2 a 4 gramos de droga vegetal al día en infusión.",
    "activePrinciples": "Hipericina, hiperforina, flavonoides, taninos.",
    "care": "Sol moderado, riego medio. Crece en terrenos baldíos y bordes de caminos.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/cf/%28MHNT%29_Hypericum_perforatum_flower_and_buttons.jpg",
    "category": "Calmante",
    "codigo": "PL-011",
    "estado": "Estable",
    "cantidad": 9
  },
  {
    "id": "lavanda",
    "name": "Lavanda",
    "scientificName": "Lavandula angustifolia Mill.",
    "benefits": ["Relajante", "Antiséptica", "Calmante del insomnio"],
    "usage": "5 a 10 gramos de droga vegetal en 150 mL de infusión. Aceite esencial.",
    "activePrinciples": "Linalol, acetato de linalilo, taninos, cumarinas.",
    "care": "Pleno sol, suelo árido o arenoso, riego escaso. Excelente drenaje.",
    "image": "https://images.unsplash.com/photo-1600699260716-d5ed9a3f9efe?w=800&q=80&auto=format&fit=crop",
    "category": "Calmante",
    "codigo": "PL-012",
    "estado": "Crítico",
    "cantidad": 5
  },
  {
    "id": "radal",
    "name": "Radal",
    "scientificName": "Lomatia hirsuta (Lam) Diels.",
    "benefits": ["Antiasmático", "Antitusivo", "Descongestionador"],
    "usage": "Infusión de dos hojas secas por taza de agua, 3-4 veces al día. Decocto de corteza.",
    "activePrinciples": "Naftoquinonas, flavonoides, taninos.",
    "care": "Prefiere semisombra o sol suave, suelo húmedo y rico en materia orgánica.",
    "image": "https://www.treesandshrubsonline.org/site/assets/files/6091/lomatia-hirsuta-6.jpg",
    "category": "Respiratoria",
    "codigo": "PL-013",
    "estado": "Bueno",
    "cantidad": 8
  },
  {
    "id": "toronjil-cuyano",
    "name": "Toronjil Cuyano",
    "scientificName": "Marrubium vulgare L.",
    "benefits": ["Digestivo", "Colerético", "Expectorante", "Cicatrizante"],
    "usage": "4,5 gramos de droga al día en infusión o uso externo para abscesos.",
    "activePrinciples": "Marrubiina (principio amargo), flavonoides, taninos, aceite esencial.",
    "care": "Pleno sol, suelo bien drenado, resistente a heladas y sequías.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Marrubium_vulgare0.jpg/250px-Marrubium_vulgare0.jpg",
    "category": "Digestiva",
    "codigo": "PL-014",
    "estado": "Bueno",
    "cantidad": 13
  },
  {
    "id": "melissa",
    "name": "Melissa",
    "scientificName": "Melissa officinalis",
    "benefits": ["Sedante", "Antiespasmódica", "Carminativa", "Antiviral"],
    "usage": "Infusión, uso interno, 2 a 3 gramos de droga vegetal, 2 a 3 veces al día.",
    "activePrinciples": "Ácido rosmarínico, aceites esenciales (citral, citronelal), flavonoides.",
    "care": "Semisombra, suelo húmedo y rico. Podas frecuentes para evitar que se descontrole.",
    "image": "https://images.unsplash.com/photo-1622576454275-729fbf6aa6eb?w=800&q=80&auto=format&fit=crop",
    "category": "Calmante",
    "codigo": "PL-015",
    "estado": "Bueno",
    "cantidad": 17
  },
  {
    "id": "menta",
    "name": "Menta",
    "scientificName": "Mentha sp.",
    "benefits": ["Antiespasmódica", "Colerética", "Carminativa", "Digestiva"],
    "usage": "Infusión de hojas. 1,5 a 3 gramos de droga en infusión, 3 veces al día después de comer.",
    "activePrinciples": "Mentol, mentona, flavonoides, taninos.",
    "care": "Mucha agua y sombra parcial. Crece de manera invasiva.",
    "image": "https://www.catalunyaplants.com/wp-content/uploads/2014/07/menta-detalle-de-hojas.jpg",
    "category": "Digestiva",
    "codigo": "PL-016",
    "estado": "Bueno",
    "cantidad": 45
  },
  {
    "id": "flor-de-la-pasion",
    "name": "Flor de la Pasión",
    "scientificName": "Passiflora incarnata",
    "benefits": ["Analgésica", "Relajante", "Sedante", "Inductor del sueño"],
    "usage": "Infusión: 1 cucharadita de hojas secas por taza de agua, 3-4 veces al día o antes de dormir.",
    "activePrinciples": "Alcaloides indólicos, flavonoides (vitexina), maltol.",
    "care": "Sol directo, riego regular. Requiere un soporte o enrejado para trepar.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Passion_Vine_NBG_LR.jpg",
    "category": "Calmante",
    "codigo": "PL-017",
    "estado": "Bueno",
    "cantidad": 12
  },
  {
    "id": "llanten",
    "name": "Llantén",
    "scientificName": "Plantago major",
    "benefits": ["Cicatrizante", "Emoliente", "Laxante", "Antiinflamatorio"],
    "usage": "Uso interno: 1,4g en 150 mL de agua, 3-4 veces al día. Uso externo: gargarismos, cataplasmas.",
    "activePrinciples": "Mucílagos, iridoides (aucubina), flavonoides, silicio.",
    "care": "Sol o semisombra, riego abundante y regular. Crece en casi cualquier suelo húmedo.",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR-hTCjMLM4Pj6EJi-peoTWofw0kQWJlmktBK5zCluwcUuisAAieuVx6PJ-dmWn-BFgZxvaNX8IXmjleY9qSynZoDhE8Hu-m0jroIb_9PPog&s=10",
    "category": "Cicatrizante",
    "codigo": "PL-018",
    "estado": "Bueno",
    "cantidad": 22
  },
  {
    "id": "romero",
    "name": "Romero",
    "scientificName": "Rosmarinus officinalis",
    "benefits": ["Colagogo", "Colerético", "Diurético", "Estimulante", "Antioxidante"],
    "usage": "Uso interno: infusión de hojas y tallos, 1 cucharadita de té por taza, 2-3 veces al día. Uso externo: compresas.",
    "activePrinciples": "Ácido rosmarínico, alcanfor, carnosol, flavonoides.",
    "care": "Mucho sol, riego muy escaso, suelo árido y bien drenado.",
    "image": "https://images.unsplash.com/photo-1607721098274-e54cbfab475d?w=800&q=80&auto=format&fit=crop",
    "category": "Estimulante",
    "codigo": "PL-019",
    "estado": "Bueno",
    "cantidad": 16
  },
  {
    "id": "ruda",
    "name": "Ruda",
    "scientificName": "Ruta graveolens L.",
    "benefits": ["Antiespasmódica", "Digestiva", "Circulatoria", "Antiinflamatoria"],
    "usage": "Uso externo preferente: compresas al 5% en luxaciones y lesiones. Uso interno muy restringido.",
    "activePrinciples": "Rutina (flavonoide), alcaloides, aceite esencial rico en metilcetonas.",
    "care": "Pleno sol, suelo pobre, riego moderado. Proteger del viento fuerte.",
    "image": "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=800&q=80&auto=format&fit=crop",
    "category": "Digestiva",
    "codigo": "PL-020",
    "estado": "Crítico",
    "cantidad": 4
  },
  {
    "id": "artemisa",
    "name": "Artemisa",
    "scientificName": "Tanacetum parthenium (L.) Sch. Bip.",
    "benefits": ["Antipirética", "Antimigrañosa", "Diurética", "Regulador menstrual"],
    "usage": "Media cucharadita de té de hojas secas y molidas al día para prevenir migrañas.",
    "activePrinciples": "Lactonas sesquiterpénicas (partenólido), flavonoides, aceite esencial.",
    "care": "Pleno sol, suelo bien drenado, riego moderado.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Feverfew.jpg",
    "category": "Calmante",
    "codigo": "PL-021",
    "estado": "Bueno",
    "cantidad": 12
  },
  {
    "id": "diente-de-leon",
    "name": "Diente de León",
    "scientificName": "Taraxacum officinale Weber",
    "benefits": ["Hepatoprotector", "Digestivo", "Diurético", "Depurativo"],
    "usage": "Raíz: 3-5g 3 veces al día. Hojas: 4-10g en infusión 3 veces al día. Jugo fresco.",
    "activePrinciples": "Principios amargos (taraxacina), inulina, flavonoides, potasio.",
    "care": "Pleno sol, suelo húmedo. Crece de forma espontánea y silvestre.",
    "image": "https://gardatxo.org/wp-content/uploads/2020/02/Diente-de-Le%C3%B3n-o-Achicoria-amarga-Taraxacum-officinale-Weber-ex-F.H.Wigg-en-Burrumba.jpg",
    "category": "Digestiva",
    "codigo": "PL-022",
    "estado": "Bueno",
    "cantidad": 30
  },
  {
    "id": "ortiga",
    "name": "Ortiga",
    "scientificName": "Urtica dioica L.",
    "benefits": ["Antiartrítica", "Diurética", "Antiinflamatoria", "Reconstituyente"],
    "usage": "3 a 5 gramos de hoja en infusión, hasta tres veces al día.",
    "activePrinciples": "Flavonoides, sales minerales (sílice, hierro), clorofila, ácidos orgánicos.",
    "care": "Semisombra, suelo muy rico en nitrógeno y materia orgánica, riego abundante.",
    "image": "https://upload.wikimedia.org/wikipedia/commons/1/16/Brennnessel_1.JPG",
    "category": "Antiinflamatorio",
    "codigo": "PL-023",
    "estado": "Bueno",
    "cantidad": 14
  },
  {
    "id": "una-de-gato",
    "name": "Uña de Gato",
    "scientificName": "Uncaria tomentosa",
    "benefits": ["Antiinflamatoria", "Antioxidante", "Inmunoreguladora"],
    "usage": "Decocción: 20 a 30 mg de extracto seco en un litro de agua.",
    "activePrinciples": "Alcaloides oxindólicos, polifenoles, glucósidos de ácido quinóvico.",
    "care": "Clima cálido y húmedo (tropical), requiere suelo rico en humus y un tutor para trepar.",
    "image": "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&q=80&auto=format&fit=crop",
    "category": "Antiinflamatorio",
    "codigo": "PL-024",
    "estado": "Estable",
    "cantidad": 7
  },
  {
    "id": "hierba-del-pano",
    "name": "Hierba del Paño",
    "scientificName": "Verbascum thapsus L.",
    "benefits": ["Expectorante", "Antitusivo", "Demulcente", "Emoliente"],
    "usage": "Uso interno: 3-4g de flores al día en infusión (dos tomas). Uso externo: compresas.",
    "activePrinciples": "Mucílagos, saponinas, flavonoides, iridoides.",
    "care": "Pleno sol, suelo bien drenado, tolera suelos secos y pedregosos.",
    "image": "https://www.gardenia.net/wp-content/uploads/2023/05/verbascum-thapsus.webp",
    "category": "Respiratoria",
    "codigo": "PL-025",
    "estado": "Estable",
    "cantidad": 6
  }
];